version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.16.5
    working_directory: /go/src/github.com/SuperJourney/CircleCI-Test
    steps:
      - checkout
      - run: go build
      - run: go test -v
  deploy:
    docker:
      - image: golang:1.16.5
    working_directory: /go/src/github.com/SuperJourney/CircleCI-Test
    steps:
      - checkout
      - run:
          name: Build binary
          command: GOOS=linux GOARCH=amd64 go build -o app
      - run:
          name: Deploy to production
          command: |
            echo "$PEM" > key.pem 
            chmod 400 key.pem
            ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@182.254.176.160 "sudo -E  docker compose -f /home/ubuntu/CircleCI-Test/docker-compose.yml up --build"
    environment:
      PEM: $PEM

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
          context: tyun

